### ISSUE TITLE
Enhance App Header with Icons

### ISSUE THREAD

**Issue by Anandsg** [Anandsg/Hungry-hero#111]
**Description:**
Our app's header currently has a simple text-based navigation with sections for Home, About, Contact, and Help. To improve the visual appeal and user experience, we should consider adding icons to the header. This enhancement will make the header more visually appealing and user-friendly.

**Proposed Changes:**
Add icons next to each navigation item in the header.
Ensure that the icons are meaningful and represent their respective sections

**Additional Information:**
- We should discuss which icons to use for each section and ensure they align with our app's design language.
- Compatibility with various devices and screen sizes should be considered during implementation.

**Tasks:**
- [x]  Research and select appropriate icons for each section.
- [x]  Implement the icon-based header in the app.
- [x]  Test the header on different devices and screen sizes to ensure responsiveness.

We have attached the image of these nav icons that we are looking for 
<img width="493" alt="Screenshot 2023-10-07 at 10 12 14 PM" src="https://github.com/Anandsg/Hungry-hero/assets/109084312/041f629e-da15-4904-9fa4-a8ea5d1a1010">

**Comment by gandholi-kumar** [comment]
Hi @Anandsg 
I'm interested in working on it, can you kindly assign this to me?

**Comment by utkarshtenguriya** [comment]
Hey @Anandsg can you assign this to me I can work on it

**Comment by gandholi-kumar** [comment]
Post changes it would look like this
![image](https://github.com/Anandsg/Hungry-hero/assets/46054848/294a021c-7ccf-4654-9be2-636da8514d72)

**Comment by Anandsg** [comment]
@gandholi-kumar small devices also needs to be handled

**Comment by gandholi-kumar** [comment]
Can you let me know which is the icon use for "Help"?

**Comment by gandholi-kumar** [comment]
> Post changes, it would appear as follows: **Large devices:** Icons are added except for `help` ![image](https://user-images.githubusercontent.com/46054848/273403352-294a021c-7ccf-4654-9be2-636da8514d72.png)
> 
> **Medium devices:** Icons were not added, need confirmation from you. ![image](https://user-images.githubusercontent.com/46054848/273406237-9b526ef9-e293-434e-b62e-46bf2b877ec1.png)

Updated the mobile screen snapshot

**Comment by Anandsg** [comment]
@gandholi-kumar Is there any related icons for help ? if so you can use that

**Comment by ChammounC** [comment]
@gandholi-kumar try using FaQuestionCircle from react-icons/fa

![Screenshot 2023-10-08 100753](https://github.com/Anandsg/Hungry-hero/assets/43007452/0204d63b-f211-47fd-9930-1aa23ddf0ec0)
