### ISSUE TITLE
[Feature request] : Add Favourite Restaurant Functionality

### ISSUE THREAD

**Issue by Anandsg** [Anandsg/Hungry-hero#12]
### Description

I would like to have the ability to add my favourite restaurants to a "Favourites" list for easy access. This feature will enhance the user experience by providing a way to quickly access and view favourite restaurants.

### Proposed Solution

- Introduce a heart icon (or any suitable icon) on each restaurant card.
- When a user clicks on the heart icon, the respective restaurant will be added to their list of favourites.
- Implement a "Favourites" page within the app, preferably located below the header and to the right side of the "Filter 4+" button. This page will display the user's favourite restaurants.

### Acceptance Criteria

- Users can click on the heart icon on a restaurant card to add it to their favourites.
- The selected restaurant should appear on the "Favourites" page.
- Users can remove a restaurant from their favourites if they wish.

- [ ]  I have checked the existing [issues](https://github.com/Anandsg/Hungry-hero/issues)
- [ ]  I have read the [Contributing Guidelines](https://github.com/Anandsg/Hungry-hero/blob/master/CONTRIBUTING.md)
- [ ]  I want to work on this issue

### Additional Information

This feature will enhance user engagement and make it easier for users to keep track of their preferred restaurants. It aligns with our goal of creating a user-friendly and enjoyable restaurant exploration experience.

### Tasks

- [ ] Implement the heart icon on restaurant cards.
- [ ] Develop the functionality to add and remove restaurants from the favorites list.
- [ ] Create the "Favourites" page and integrate it into the app's layout.
- [ ] Test the feature thoroughly to ensure it works seamlessly.
- [ ] Update the app's documentation to include information about this new feature.

### Contribution Guidelines

- Please fork this repository and create a feature branch for this task.
- Follow our coding style and conventions (if any) as outlined in our project's guidelines.
- Feel free to reach out for any clarifications or assistance during the development process.

### Additional details
**Please refer to the similar feature screenshot which we are going to implement for a visual representation of this feature.**
<img width="1416" alt="Screenshot 2023-09-26 at 8 38 46 PM" src="https://github.com/Anandsg/Hungry-hero/assets/109084312/11b830c1-e4d9-451c-ba87-f7b4fc99b7b7">

Let's make our restaurant exploration app even better by adding this exciting feature! Contributors, please indicate your interest in working on this issue. Let's collaborate to make it happen.

**Comment by reyrinbafs** [comment]
Hey Anand, I would like to work on this issue.

**Comment by Anandsg** [comment]
@reyrinbafs have you worked on any react project ?

**Comment by mohitsaini07** [comment]
Hi Anand, I would like to work on this issue.

**Comment by Anandsg** [comment]
@LynxSumit you can work on it

**Comment by Anandsg** [comment]
@LynxSumit done, thanks for the follow up.

**Comment by ShahIsCoding** [comment]
Helllo @Anandsg i know i was not assigned this issue but seemed interesting so i have solved it and generated a pull request could you have a look

**Comment by Anandsg** [comment]
feature has been deployed hence closing the issue
