### ISSUE TITLE
[Feature] : Fix Duplicate Restaurant Entries in Cart

### ISSUE THREAD

**Issue by Anandsg** [Anandsg/Hungry-hero#8]
**Issue Title:**

Duplicate Restaurant Entries in Cart

Issue Description:

**Problem:**

Currently, when a user adds the same restaurant to their cart, it's being duplicated, resulting in two identical entries. This can be confusing and is not an optimal user experience.

**Proposed Solution:**

We're looking for a talented contributor to develop a feature that will update the cart's quantity for the same restaurant instead of adding it as a separate entry. This enhancement will not only make our cart functionality more user-friendly but also streamline the ordering process.

**Task Checklist:**

- [ ]  Develop a feature to check if the restaurant already exists in the cart.
- [ ]  If the restaurant is already in the cart, update the quantity instead of creating a new entry.
- [ ]  Ensure that the cart UI reflects the changes in real-time.
- [ ]  Test the feature thoroughly to avoid any unintended side effects.
- [ ]  Update the documentation with any changes made.

**👥 Contributor Guidelines:**

- Please fork the repository and create a new branch for your work.
- Follow the coding style and standards of the project.
- Ensure that your code is well-documented and easy to understand.
- Submit a Pull Request when you're ready for your changes to be reviewed and merged.
<img width="1432" alt="Screenshot 2023-09-25 at 2 00 26 PM" src="https://github.com/Anandsg/Hungry-hero/assets/109084312/6c489e28-7b06-4a1d-8193-79bae331a714">

This enhancement will greatly improve the user experience of our app, and we're excited to see it implemented. Feel free to ask questions or seek clarification if needed. Happy coding

**Comment by ronisarkarexe** [comment]
@Anandsg Could you please assign me this task also?

**Comment by Anandsg** [comment]
Hi @ronisarkarexe  Sure, you can begin working on this once you've fixed issue #9  We'll handle each issue separately since we can't merge them all at once. Hope that's clear! thanks for contributing.

**Comment by Anandsg** [comment]
you can work on this also @ronisarkarexe

**Comment by Shahidkhatrii** [comment]
I am interested in contributing to this issue as I also came across similar problem few days ago
And I also want to contribute to Authentication functionality in Hacktoberfest

**Comment by Anandsg** [comment]
@Shahidkhatrii Sure you can work on this issue please make sure to install CORS extension to run this app in local machine, assigning the issue to your bucket.
